/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany._usjt_psc_sistema;

import java.awt.Toolkit;

import com.mycompany._usjt_psc_sistema.DAOS.UserDAO;
import com.mycompany._usjt_psc_sistema.models.User;
import com.mycompany._usjt_psc_sistema.screens.AdminDashboardScreen;

import helpers.GenreNames;

/**
 *
 * @author Usuario
 */
public class UserEdit extends javax.swing.JFrame {

        /**
         * Creates new form UserEdit
         */
        public UserEdit() {
                super("MyBookshelf - Editar Informações");
                setIconImage(Toolkit.getDefaultToolkit().getImage("src/assets/duke.png"));
                initComponents();
                this.setLocationRelativeTo(null);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                userIdField = new javax.swing.JTextField();
                userNameField = new javax.swing.JTextField();
                userSurnameField = new javax.swing.JTextField();
                userAgeField = new javax.swing.JTextField();
                userEmailField = new javax.swing.JTextField();
                userGenderBox = new javax.swing.JComboBox<>();
                userTypeField = new javax.swing.JComboBox<>();
                jComboBox1 = new javax.swing.JComboBox<>();
                jComboBox2 = new javax.swing.JComboBox<>();
                confirmEditionButton = new javax.swing.JButton();
                cancelButton = new javax.swing.JButton();
                userPasswordField = new javax.swing.JPasswordField();
                String[] genreNames = GenreNames.getGenreNames();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Usuário"));

                userIdField.setBorder(javax.swing.BorderFactory.createTitledBorder("ID do Usuário"));

                userNameField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome do Usuário"));

                userSurnameField.setBorder(javax.swing.BorderFactory.createTitledBorder("Sobrenome do Usuário"));

                userAgeField.setBorder(javax.swing.BorderFactory.createTitledBorder("Idade do Usuário"));

                userEmailField.setBorder(javax.swing.BorderFactory.createTitledBorder("Email do Usuário"));

                userGenderBox.setModel(
                                new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
                userGenderBox.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));

                userTypeField.setModel(
                                new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Padrão" }));
                userTypeField.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Usuário"));

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(genreNames));
                jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder("Primeiro Gênero Favorito"));

                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(genreNames));
                jComboBox2.setBorder(javax.swing.BorderFactory.createTitledBorder("Segundo Gênero Favorito"));

                confirmEditionButton.setText("Confirmar Edição");
                confirmEditionButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                confirmEditionButtonActionPerformed(evt);
                        }
                });

                cancelButton.setText("Cancelar");
                cancelButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonActionPerformed(evt);
                        }
                });

                userPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha do Usuário"));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jComboBox1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                239,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(jComboBox2,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                239,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                false)
                                                                                                                                .addComponent(userEmailField,
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(userNameField,
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                180,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(userGenderBox,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                210,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                .addComponent(userTypeField,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                116,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(userSurnameField,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                210,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                .addComponent(userAgeField,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                116,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                .addComponent(userIdField,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                106,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(183, 183, 183)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(confirmEditionButton,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(cancelButton,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                169,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(userPasswordField))))
                                                                .addContainerGap(12, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(15, 15, 15)
                                                                .addComponent(userIdField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(userNameField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                48,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(userSurnameField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(userAgeField))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE,
                                                                                                false)
                                                                                .addComponent(userEmailField)
                                                                                .addComponent(userGenderBox)
                                                                                .addComponent(userTypeField,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                48,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(20, 20, 20)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jComboBox1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                48,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jComboBox2))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(userPasswordField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                39,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(confirmEditionButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 21, Short.MAX_VALUE)
                                                                .addComponent(cancelButton,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                38,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(14, 14, 14)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(17, 17, 17)
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(24, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
                this.dispose();
                AdminDashboardScreen ads = new AdminDashboardScreen();
                ads.setVisible(true);
        }// GEN-LAST:event_cancelButtonActionPerformed

        private void confirmEditionButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_confirmEditionButtonActionPerformed
                int getterUserId = Integer.parseInt(userIdField.getText());
                String getterUserName = userNameField.getText();
                String getterUserSurname = userSurnameField.getText();
                String getterUserEmail = userEmailField.getText();
                String getterUserAge = userAgeField.getText();
                String getterUserGender = userGenderBox.getSelectedItem().toString();
                String getterUserPassword = new String(userPasswordField.getPassword());
                int getterUserFirstGenre = jComboBox1.getSelectedIndex() + 1;
                int getterUserSecondGenre = jComboBox2.getSelectedIndex() + 1;
                boolean getterUserType = userTypeField.getSelectedItem().toString().equals("Administrador");

                try {
                        if (getterUserName.equals("") || getterUserSurname.equals("") || getterUserEmail.equals("")
                                        || getterUserAge.equals("") || getterUserPassword.equals("")) {
                                javax.swing.JOptionPane.showMessageDialog(null,
                                                "Preencha todos os campos corretamente!");
                        } else {
                                User user = new User(getterUserId, getterUserName, getterUserSurname, getterUserEmail,
                                                getterUserPassword, getterUserAge, getterUserGender,
                                                getterUserFirstGenre,
                                                getterUserSecondGenre, getterUserType);
                                UserDAO userDAO = new UserDAO();
                                userDAO.update(user);
                                this.dispose();
                                AdminDashboardScreen ads = new AdminDashboardScreen();
                                ads.setVisible(true);
                        }

                } catch (Exception e) {
                        // TODO: handle exception
                }
        }// GEN-LAST:event_confirmEditionButtonActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(UserEdit.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(UserEdit.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(UserEdit.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(UserEdit.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new UserEdit().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton cancelButton;
        private javax.swing.JButton confirmEditionButton;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JComboBox<String> jComboBox2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JTextField userAgeField;
        private javax.swing.JTextField userEmailField;
        private javax.swing.JComboBox<String> userGenderBox;
        private javax.swing.JTextField userIdField;
        private javax.swing.JTextField userNameField;
        private javax.swing.JPasswordField userPasswordField;
        private javax.swing.JTextField userSurnameField;
        private javax.swing.JComboBox<String> userTypeField;
        // End of variables declaration//GEN-END:variables
}
